### ISSUE TITLE
How to use the

### ISSUE THREAD

**Issue by v1c77** [pavouk-0/postgres-xl-docker#11]

**Comment by v1c77** [comment]
Hello, I started use the version 0.1.0  two weeks ago. Now I have a swarm cluster, but i don't know how to deploy the new version on it. Can someone  tell me how to do that? Thank you.

I have to create at least 10 data_node and more coord node. Is it easier to use swarm?

**Comment by tiredpixel** [comment]
@woailuoli993, glad to hear you're using it! :)

I agree with using a Docker Swarm cluster over the Docker Compose method in deployment; that is how I myself am using it. However, I have switched to the Docker Compose method as the default so people can get running easily, and can potentially also contribute to the project. It also provides a really easy way to integrate with other projects in development, as it's possible to simply declare a shared network, and then to be able to develop other projects against a fully-functioning cluster running locally (I'm doing this for one non-trivial project).

Version 0.2.0 is an update of approach and packaging, but not to the Postgres-XL itself. Thus, if you've already deployed it and are running important things, I might not switch to 0.2.0, myself. The only thing you might like to check is any co-location preferred treatment between coordinators and datanodes, and potentially any additional (GTM) proxies.

If you were creating a new cluster from scratch, however, I would advise you to go with 0.2.0, since it has a more streamlined installation, supports a great variety of configurations, and doesn't require the running of SSH behind Supervisor or the cross-node authentication of keys. As a rough estimate, I think I've cut the complexity to around half, with 0.2.0, whilst perhaps adding at least half to the potential. In such a deployment, I would use the `docker-compose.yml` as reference to define your own Docker Swarm services, much like for 0.1.0, but without requiring the SSH volumes or indeed the control container itself. If you choose to do this and need any help, please feel free to report back with any questions, and I'll gladly guide you through it. :)

**Comment by tiredpixel** [comment]
p.s. There is one other point, which is that even if you have data, you can probably just define a new service attached to the old volume. The mount point has changed (https://github.com/tiredpixel/postgres-xl-docker/blob/0.1.0/Dockerfile#L102, https://github.com/tiredpixel/postgres-xl-docker/blob/0.2.0/Dockerfile.coord.Dockerfile#L6), but so long as there is a `data/` directory underneath, then things should probably be fine. I wouldn't recommend this unless you're trying to migrate, though, as it's a needless complication if you don't actually have any data to preserve.

**Comment by tiredpixel** [comment]
p.p.s. Oh, wait—that *would* actually be more complex; 0.1.0 nests under `coord/` or `data/` directories, whereas 0.2.0 no longer needs to, so goes for simply `data/`. So you would actually need to move the directories in the volume.

**Comment by v1c77** [comment]
@tiredpixel  Thanks for your answer, I just want to create a new cluster, There is no need to migrate.

**Comment by tiredpixel** [comment]
@woailuoli993, you're welcome. In that case, I would go straight for 0.2.0, and forget all about 0.1.0 except possibly as a hint in how to define Docker Swarm services (although it is not quite the same). I haven't written any instructions for this for 0.2.0, yet, but if you define your services, I would be happy to look the definitions for you.

**Comment by v1c77** [comment]
@tiredpixel My pleasure.
