### ISSUE TITLE
Make the init.sh scripts idempotent?

### ISSUE THREAD

**Issue by alexanderkjeldaas** [pavouk-0/postgres-xl-docker#13]
The installation could possibly be simplified if the `init.sh` scripts were made idempotent.  For example they could add a file to the data directory indicating that they have been run.

**Comment by tiredpixel** [comment]
@alexanderkjeldaas, thanks for your suggestion. Are they not idempotent, though? I haven't actually checked, but I think they fail on the second run, without damage? Also, these are manual steps; what scenario do you foresee where someone would run them moree than once? If we did need to do such, we wouldn't need to add a file; we could simply check within the pg data directory. :)

**Comment by alexanderkjeldaas** [comment]
I'm bringing up complete docker environments for every PR I submit.  That's a use-case where I wouldn't want to have any manual steps.

It is quite uncommon to have manual steps in dockerized applications - usually it is all managed using environment variables.

If they fail, is it idempotent?  I was thinking that the `init.sh` scripts should check whether `initdb` can be run or not, and only run `initdb` if needed.

Or if `initdb` fails, then run 
```
initdb ... || /bin/true
```

**Comment by tiredpixel** [comment]
Yes, it can be uncommon to have manual steps in Docker applications. But it is not so uncommon to have manual steps for clustering nodes. But I realise that what you're referring to here is the initialisation itself.

I did originally do a test for init, but I rewired it because of wanting to ensure the command point was handed off correctly to Process 1 rather than a child process. Otherwise, tracking pids becomes more important.

But what you ask should be possible, because the main PostgreSQL image surely needs to do the same thing. I'll try to take a look when I get some time.

**Comment by tiredpixel** [comment]
@alexanderkjeldaas, just a follow-up: I haven't forgotten about this, and l will hopefully add it before too long, when I get some free moments… I've also been working on adding healthchecks, and intend to also make some other improvements. Stay tuned! :)

**Comment by tiredpixel** [comment]
@alexanderkjeldaas, I've just added it. All nodes should now auto-initialise on boot, removing the need to boot with `init.sh` or similar. If you try it out, please let me know! :) I'll release in a bit; got one task left for this round of work for the new version.
