### ISSUE TITLE
Question - Image Size

### ISSUE THREAD

**Issue by stephenstubbs** [pavouk-0/postgres-xl-docker#30]
Hi,

I'm busy adding in slave functionality into a pull request. I'm not sure why but when I build the image based on the included dockerfile its 498mb compared to yours on dockerhub which is 128mb. Any idea why there is such a massive difference in image size?

**Comment by tiredpixel** [comment]
There are two Dockerfiles—`Dockerfile`, and `ci/Dockerfile`. The top-level one is used for development, and contains all the things necessary for compiling, etc. The `ci/` one is used by our CI system at Pavouk, and copies across the compiled binaries only onto a clean Debian image. That's almost certainly the difference in size you're seeing. If you want to try building the CI version… well… I'm not sure there's much point; there's nothing that will run automatically in the repo, since it depends on various things we have in-house, and although it's possible to step through it manually (following the YAML files and Shell files), there's likely no point. Basically, there results in the compiled binaries being copied into the Postgres-XL path, with presumptions of all the same architecture, etc.

**Comment by tiredpixel** [comment]
p.s. When I say development, that's not strictly true in this case, of course, since the binaries get copied across. This is a pattern we use for other projects, however, such as Haskell ones, and find very powerful. Basically, everything uses the 'development' copy, and dependencies come from there, and even external libraries are bit-level-frozen wherever possible (less of a concern, here, but it does in fact still happen, effectively). I've found this to be a far more powerful method that simply cleaning the compiled artefacts in-layer (although of course that would allow the same sizes of images to be arrived at, in most cases), or having multiple 'development' vs 'production' Dockerfiles (a design I don't like, or approve of, in general—but I'll admit that in this case that can be somewhat of a naming nuance).

**Comment by stephenstubbs** [comment]
Ok thanks a lot. I've just used a multistage dockerfile for now and have the size down to something similar. Not quite as small but good enough for my use.

**Comment by stephenstubbs** [comment]
Here it is just for anyone else who might have the same issue. I'm just using the tarball rather than using the source as I always have issues with WSL messing with line endings and this is just easier for me. Pgbouncer is included as I intend to run it for each coordinator with haproxy in front loadbalancing between them.

```
#===============================================================================
FROM debian:10 AS builder

ARG PG_HOME=/var/lib/postgresql
ARG PG_LIB=/usr/local/lib/postgresql
ARG PG_USER=postgres
#-------------------------------------------------------------------------------
RUN apt-get update && \
    apt-get install -y --no-install-recommends \
        # postgres xl requirements
        bison \
        build-essential \
        daemontools \
        flex \
        libreadline-dev \
        netcat \
        zlib1g-dev \
        # fix locales
        # curl for downloading libs and certs for https
        ca-certificates \
        curl && \
        rm -rf /var/lib/apt/lists/*
#-------------------------------------------------------------------------------
RUN useradd ${PG_USER} -d ${PG_HOME} && \
    mkdir -p ${PG_LIB} ${PG_HOME} && \
    chown -R ${PG_USER}:${PG_USER} ${PG_LIB} ${PG_HOME}
#-------------------------------------------------------------------------------
WORKDIR ${PG_HOME}
RUN curl -sf https://www.postgres-xl.org/downloads/postgres-xl-10r1.1.tar.gz -o postgres-xl-10r1.1.tar.gz && \
    tar -xvf postgres-xl-10r1.1.tar.gz && \
    rm postgres-xl-10r1.1.tar.gz && mkdir lib && mv postgres-xl-10r1.1 lib/postgres-xl && chown -R postgres:postgres lib
#-------------------------------------------------------------------------------
USER ${PG_USER}
WORKDIR ${PG_HOME}/lib/postgres-xl
RUN ./configure --prefix ${PG_LIB} && \
    make
#-------------------------------------------------------------------------------
USER root
RUN make install
#-------------------------------------------------------------------------------
RUN cd ${PG_HOME}/lib/postgres-xl/contrib/pgcrypto && make && make install
RUN cd ${PG_HOME}/lib/postgres-xl/contrib/ltree && make && make install
RUN cd ${PG_HOME}/lib/postgres-xl/contrib/cube && make && make install
#-------------------------------------------------------------------------------
COPY bin/* ${PG_LIB}/bin/
RUN rm -rf ${PG_HOME}/lib
#===============================================================================

#===============================================================================
FROM debian:10

ARG PG_HOME=/var/lib/postgresql
ARG PG_LIB=/usr/local/lib/postgresql
ARG PG_USER=postgres
#-------------------------------------------------------------------------------
RUN apt-get update && \
    apt-get install -y --no-install-recommends \
        libreadline-dev \
        netcat \
        locales \
        pgbouncer && \
    rm -rf /var/lib/apt/lists/*
#-------------------------------------------------------------------------------
RUN sed -i -e 's/# en_US.UTF-8 UTF-8/en_US.UTF-8 UTF-8/' /etc/locale.gen && \
    locale-gen
#-------------------------------------------------------------------------------
COPY --from=builder ${PG_HOME} ${PG_HOME}
COPY --from=builder ${PG_LIB} ${PG_LIB}
#-------------------------------------------------------------------------------
USER ${PG_USER}
WORKDIR ${PG_HOME}
ENV PATH=${PG_LIB}/bin:$PATH \
    PGDATA=${PG_HOME}/data \
    PG_USER_HEALTHCHECK=_healthcheck

ENV LANG en_US.UTF-8
ENV LANGUAGE en_US:en
ENV LC_ALL en_US.UTF-8
#-------------------------------------------------------------------------------
VOLUME ${PG_HOME}
#===============================================================================
```

**Comment by tiredpixel** [comment]
Okay, thanks a lot. I don't think I see a reason to change this, at present, since most people won't be developing it, but only using it from the images, and I suspect many developing it won't mind too much about the larger image sizes. By the time something's accepted, it'll go into the main release anyway, including with the smaller images we publish. And of course, if anyone wants to split off and release their own images, for some reason, they'll likely have their own CI or post-packaging anyway, so that's up to them. I'll close this, but thanks a lot for posting your approach in case it's useful to anyone else.
