### ISSUE TITLE
Orchestration

### ISSUE THREAD

**Issue by stephenstubbs** [pavouk-0/postgres-xl-docker#34]
Hi,

I know this is probably unrelated as this project is for people to get a basic cluster setup when needed and for that it's great. I am having a hard time getting what I need stable. I am in the process of moving over to kubernetes and trying to set it up that way rather.

Perhaps once done I can setup a helm chart which links to this image if that would be useful and is possible without too much modification. The main blockers on docker swarm for me are the healthchecks and ordering of container startup as well not being able to setup affinity without labels which won't allow a ha setup.

I'll be starting out based on these.
https://www.digitalocean.com/community/tutorials/how-to-migrate-a-docker-compose-workflow-to-kubernetes
https://severalnines.com/database-blog/running-galera-cluster-kubernetes

Been moving over a lot of my other apps without too much hassle as jenkins x is awesome.

**Comment by tiredpixel** [comment]
Interesting. Well, the aim is not just for the basics; it's intended to work for far more complex setups, too, so I'm willing to add small improvements to make that easier. I haven't given the latest images a try in K8S, but I'm not aware of any problems with it, including with setting affinity (which of course is possible in Swarm, too).

I, too, have had issues with stability in the past, though—but I'm not convinced that this is because of the Docker images (although it could well be); it was also my experience of Postgres-XL, even with more traditional setups (such as using `pgxc_ctl`). I've found before that the GTM in particular seems to be very temperamental, at times, and I've lost count of how many times I've had errors like the metadata becoming corrupted between nodes, or the min-tx-id becoming out-of-sync. Perhaps the latter, at least, has some kind of simple fix; I sadly don't know enough about the internals of Postgres-XL to have found one, however (despite much extensive searching). The former, I suspect, is far more serious, and hard to fix in any sensible way.

I do wonder, how many places are actively using Postgres-XL in a very stable setup. Indeed, much of the motivation for adding the healthchecks in the beginning was to deal with network issues in a more reliable manner, as I found in the past that even ones set up with `pgxc_ctl` would freeze and become unresponsive, and at times require nodes to be restarted in a specific order. Hence the healthchecks, which normally should at least ensure the cluster converges and becomes stable after a network-related event (assuming working, which is an assumption, I know).

Thanks for the links. The SeveralNines one is a couple of years old, and in that time I've seen Swarm gradually gain more of the features that K8S has. This is part of the downside of the whole Docker ecosystem, in my increasing view; even a year is a huge amount of time, and things change very fast and often not that stably. Even the last versions of Docker with Swarm, for example, seem to have various memory-related bugs, and I get various crashes unpredictably and for no clear reasons. I'm beginning to wonder if a high degree of stability—at least compared to alternative, more tradition, solutions—is even possible that easily using Docker, at least without adding various other layers of HA in front, or indeed using other orchestrators (and maybe even then). For historical reasons, most of my work at present is around Swarm, rather than K8S, so I've been watching and updating with each new version for some years. But if I started again, and could justify the significant time it would take to remap and migrate everything to K8S, I'd very probably go in that direction (or, perhaps even in the Nomad or Mesos direction). I would expect, though, these images to work on all those orchestrators, and I'm happy to accept patches where they don't (unless they're large in scope, or require changing things significantly). I haven't used Jenkins X, so thanks for the tip on that.

Have you had chance to try the new images released just before the weekend? I'd be very interested to hear whether it improves your healthcheck experience or not, regardless of the orchestrator.
https://www.pavouk.tech/2019/09/20/postgres-xl-docker-releases/

**Comment by stephenstubbs** [comment]
Thanks a lot for looking at this and the detailed reponse. Let me try the new image with docker swarm and let you know. I have made my mind up to move over to k8s for the rest of my workload but will be good to see if it is more stable in docker swarm. The affinity in docker swarm is based on labels on the nodes which will be lost if those nodes go down. As far as I can tell k8s lets you set affinity in relation to other pods which is really what I'm after as I want a coordinator and datanode to run on each node and their slaves on a different node. and the gtm and gtm slave to run on different nodes. This becomes a real pain with docker swarm labels. 

I am happy this project is for big deployments too. I will then base my helm chart off of this and do a pull request for changes if needed.

**Comment by stephenstubbs** [comment]
I didn't see this issue. https://github.com/pavouk-0/postgres-xl-docker/issues/35 I will rather start testing that helm chart than starting a new one.

**Comment by tiredpixel** [comment]
@sstubbs, ah, I see. Yes, for that sort of affinity complexity, Kubernetes is indeed far superior to Docker Swarm. Yes, from memory, you should be able to do what you're thinking with Kubernetes. I'd be very interested to hear your experiences with how they compare, stability-wise—but equally, such would have to involve quite a few iterations of creating and running new clusters, in order for the stats to have value, since in my experience the stability depends a whole lot on what happens during the first few minutes of bootstrapping. :P

Yes, as far as I'm concerned, this should be the go-to Docker image for Postgres-XL. It's not an official image (it's never been blessed, and I'm not a Postgres-XL maintainer or dev), but I humbly suggest that there isn't another Docker image attempt for Postgres-XL which has had anywhere near as much thought, research, and testing put into its development. That's not to say it's without its problems—this we both know—but I think it's a very solid base, which should be as production-suitable as Postgres-XL itself in some cases, and I'd like it to be the go-to for Swarm, Kubernetes, and maybe more. That does depend, of course, on how much interest there is—but during its life so far, it has gathered and seems to be gathering an increasing interest. :)

**Comment by stephenstubbs** [comment]
OK brilliant I'll definitely keep you posted about what I find. This image just keeps getting better and better even though it was a brilliant image to begin with. :) I remove and create a lot of clusters for testing purposes. So I should have a pretty good results for you. I will still do testing of docker swarm too to try and catch issues if any with the image itself.

**Comment by tiredpixel** [comment]
Thank you for your kind comments; those are very encouraging to read. :) Looking forward to hearing the results of your testing.

**Comment by tiredpixel** [comment]
Kindly note this serious issue, which is a potential upstream bug (as yet unconfirmed and unreported):
https://github.com/pavouk-0/postgres-xl-docker/issues/37

**Comment by tiredpixel** [comment]
Should we still keep this issue open?

**Comment by stephenstubbs** [comment]
Yes this can be closed.
