### ISSUE TITLE
Helm Chart

### ISSUE THREAD

**Issue by LamaAni** [pavouk-0/postgres-xl-docker#35]
Hi,

I have started building a helm chart for this image, which I intend to publish soon. Though, there was a change in the last images from ~10 days ago where "netcat" was removed from the 10 image. 

Anyway you could return this package, or give an equivalent?
Also, what is the recommended stable PGXL-10 image? Is it on docker hub?

**Comment by LamaAni** [comment]
Helm chart beta is here: https://github.com/LamaAni/PGXL-HELM

**Comment by stephenstubbs** [comment]
Brilliant! Thank you very much. I was going to start looking at this today but I'm very new to k8s.

**Comment by LamaAni** [comment]
> Brilliant! Thank you very much. I was going to start looking at this today but I'm very new to k8s.

Hi, sure! Just please remember that this is a week old :) This is beta. Please, if you can, contribute anything you find.

**Comment by stephenstubbs** [comment]
Understood. Thanks yes I will definitely let you know.

**Comment by tiredpixel** [comment]
Hi, @LamaAni; thanks for your interest. Very pleased to hear you, too, are doing some work on this. :) I'm not personally currently in a position to be able to test your Helm chart—I'm very low on time in general, including for this project, and am not currently doing much with Kubernetes, unlike some times in the past—but I'm very interested to see how it progresses. Thank you, @sstubbs, for offering to help test it (@sstubbs has been helpful to the project over the last few months, and helping to get some more testing on the core images itself). Let me know what advice you need along the way (including for things like the images and healthchecks).

Netcat was indeed removed in the last few days. It was used only for the GTM healthcheck, which has now been replaced by the one using pgxc_monitor (which was based on discussions with @sstubbs, and a suggestion by @JuliuszJ who suggested using it to get rid of the magic string I was experimenting with). I have no current intention to add it back; why do you need it? :)

Glad you asked; there was a new release just 2 days ago. :) The lastest stable Postgres-XL 10 image is Docker Hub `pavouk0/postgres-xl:XL_10_R1_1-313-g31dfe47`. Kindly see our blog post announcing the lastest builds (since Postgres-XL Docker was adopted as a project of Pavouk, we're maintaining it there as one of our contributions back to the open-source community):
https://www.pavouk.tech/2019/09/20/postgres-xl-docker-releases/

**Comment by tiredpixel** [comment]
Kindly note this serious issue, which is a potential upstream bug (as yet unconfirmed and unreported):
https://github.com/pavouk-0/postgres-xl-docker/issues/37

**Comment by LamaAni** [comment]
Since in kubernetes, the generation of pods is asynchronous, I an using netcat to validate all internal resources are met before starting the datanodes. I found this to be very helpful for triggering the right sequence for the case of startup and restart. There are two major checks.

1. When handling persistence, (destroy the cluster + restart the cluster or on cluster failure) the start sequence is of the at-most importance. I have found that in cases where the cluster starts in the wrong order I get fatal errors. (Sorry did not note done which those where). I am using netcat in the method attached below to sync the startups. 
2. Health check which dose not depend on the database. There are two checks that are best added in kubernetes, the first is livelinessProbe, and readinessProbe. See here: https://kubernetes.io/docs/tasks/configure-pod-container/configure-liveness-readiness-startup-probes/ . For these I do require netcat, when I am checking all the other pods are alive are ready. (Coordinator).
3. When working on kuberntes, and due to its nature, sometimes pods are destroyed. In this case it is best to disconnect the service from the coordinators using the redinessProbe. I am using netcat for that as well. 

Probe methods can be found in the templates/bash_scripts 
Main wait_for_port method:
```shell
    #!/usr/bin/env bash
    # Helper method, wait for connection.
    # Usage: wait_for_connection [hostname] [port]
    HOST=$1
    PORT=$2
    : ${PORT_WAIT_INTERVAL:="1"}
    : ${PORT_WAIT_TRIES:="60"}
    : ${PORT_WAIT_TIMEOUT:="1"}
    echo "$LOGGING_PREFIX Checking $HOST:$PORT is open with an interval of $PORT_WAIT_INTERVAL, max $PORT_WAIT_TRIES times.."
    WAIT_INDEX=0
    while true; do
      nc -w $PORT_WAIT_TIMEOUT -zv "$HOST" "$PORT" &> /dev/null
      if [ $? -ne 0 ]; then
        if [ $WAIT_INDEX -gt $PORT_WAIT_TRIES ]; then
          echo "$LOGGING_PREFIX Error, timedout while waiting for port $PORT on $HOST"
          exit 2
        fi
        echo "$LOGGING_PREFIX Port $PORT not available on $HOST, retry in $PORT_WAIT_INTERVAL"
      else
        echo "$LOGGING_PREFIX Port $PORT is open on $HOST"
        break
      fi
      WAIT_INDEX=$((WAIT_INDEX+1))
      sleep "$PORT_WAIT_INTERVAL"
    done
```

**Comment by tiredpixel** [comment]
Thanks for your detailed reply, @LamaAni.

> Since in kubernetes, the generation of pods is asynchronous,

Start-up order of services in Swarm is also non-deterministic; it's worth noting that most of the issues you describe here for Kubernetes are the same as for Swarm (note that `depends_on` is not supported for Swarm).

> triggering the right sequence for the case of startup and restart

In case it's helpful, extensive debugging stuff on Postgres-XL clusters in the early days of this project (around 2 years ago) led me to decide that the safest startup order is almost certainly: GTM, Datanodes, Coordinators. My experience of Postgres-XL is that it's very sensitive to issues, and almost never recovers on its own after a networking event or other issue—hence the significant work on healthchecks.

> When handling persistence, (destroy the cluster + restart the cluster or on cluster failure) the start sequence is of the at-most importance. I have found that in cases where the cluster starts in the wrong order I get fatal errors. (Sorry did not note done which those where). I am using netcat in the method attached below to sync the startups.

I'm guessing these were errors to do with the GTM transaction id, or perhaps wraparound. Or maybe a node-undefined within the metadata error.

> Health check which dose not depend on the database. There are two checks that are best added in kubernetes, the first is livelinessProbe, and readinessProbe. See here: https://kubernetes.io/docs/tasks/configure-pod-container/configure-liveness-readiness-startup-probes/ . For these I do require netcat, when I am checking all the other pods are alive are ready. (Coordinator).

Interesting—we're taking the opposite approach, here. :) You're looking to define healthchecks which work at a container level thus allowing health of the pod to be ascertained, whereas I'm looking to define healthchecks which work at a cluster level, purposely requiring the database to be not only connected to, but exercised non-trivially (to get around various errors experienced in the past where Postgres-XL would be up and seem healthy, even for reads, until the first write caused it to explode).

> When working on kuberntes, and due to its nature, sometimes pods are destroyed. In this case it is best to disconnect the service from the coordinators using the redinessProbe. I am using netcat for that as well.

Swarm services, too, can have containers within them relaunched, so I think this is similar. Admittedly, some of how this works depends on the deployment strategy and whether containers are permitted to be booted in parallel (similar to Kubernetes `rollingUpdate` default strategy)—but this for a database would terrify me. :)

I'm curious: is there a reason why you're not using any of the `docker-healthcheck-data`, etc. healthchecks present in the image? Or in indeed the `docker-cmd-data` and `docker-entrypoint-data` which initalialises the database already using `docker-init-data`?

Notwithstanding my comments above, it seems like there's a good use-case for adding Netcat back in; I'll accept a PR. :) It should be `ci/Dockerfile` at a minimum, and `Dockerfile` additionally if you also want it present when building locally from source (rather than just in the final image). Please see https://github.com/pavouk-0/postgres-xl-docker/commit/9e2d43a5e0e8ec74105a2e6da5302acdc66d8d18#diff-cfd2b863eadb60a3df51a7240158dba1 for details.

**Comment by LamaAni** [comment]
1. :) I found that if I make sure all nodes are up and running, and then trigger the startup the sequence (pg or gtm) I get a more stable boot - event if I delete one of the nodes manually during stratup - which is kinda awsome. The important thing though is that the gm and proxy are up. I am very interested in the differences.  

2. Your guess is probably correct. For this case exactly I persisted the data of the GTM, which allowed me to crash it and result in a successful recovery (while querying). While its crashed I use nc to detect and disable the coordinators, thus removing external influences while the restart is happening. 

3. I plan on doing both pods and db check. But keep the db check internal (currently using pg_isready) and external pod check using the network. The redinessProbe would disconnect the pod from the network in the case where the pg_isready fails. Would love a more "official" approach to do an internal check, and understand the health_checks more. I used this method since I did not understand the results of the health_check, and what it says exacly.

4. The reason I decided not to use the internal scripts was that I wanted to control the configuration using helm. In this case, I want the helm chart to completely configure the execution (and allow for overrides). Plus, the scripts add some networking commands where in the current implementation I made an assumption that the network is completely open; since this is a new image, I assumed that changes to the boot-up were bound to happen. Finally, I wanted more logs and did not feel it would be appropriate at this time to request these are added to the image. I must say though, I relied heavily on your code and the additions were mostly for stability, sequencing and logging in the kub cluster. I find the code itself clear and usable. If you like, we can definitely work together to bring some of these ideas into the image - and then morph the helm chart to join on these. I would prefer that. 

5. Will add a pr for Netcat. Thank you!!

**Comment by LamaAni** [comment]
PR is up: 
https://github.com/pavouk-0/postgres-xl-docker/pull/40

**Comment by tiredpixel** [comment]
Is this able to be closed, now the PR has been merged?

**Comment by LamaAni** [comment]
@tiredpixel Yes thank you.
