### ISSUE TITLE
Release tag names

### ISSUE THREAD

**Issue by LamaAni** [pavouk-0/postgres-xl-docker#41]
Hi,

Would it be possible to change the format of the release tag names (for the docker image), to a more human readable format? 

I would suggest,
[pgxl_version_number]-[docker-image-version],

for example,
postgres-xl-docker:10.1-0.5.1

That would increase the readability in the helm chart. See: https://github.com/LamaAni/PGXL-HELM
image value.

**Comment by tiredpixel** [comment]
The tags were actually cleaned up slightly in the last release. :) When a new version gets released, it's tagged according to the tag in the upstream Postgres-XL repo. Since the build images themselves aren't part of the official Postgres-XL project, a build change, even to fix a bug, won't result in a version bump upstream, of course. So, the base tag is done to match the upstream, so it's clear which upstream code is actually being packaged, and then anything past that is incremented using Git tag (i.e. using `git describe`) command, so it's deterministic. So, for the release `XL_10_R1_1-313-g31dfe47342`, since that was a version released by this project rather than an intermediary build, that name actually came from Postgres-XL—if you check out Postgres-XL `XL_10_STABLE` branch, you'll see that that commit is called `XL_10_R1_1-313-g31dfe47342`.

I agree the tags are a bit complex, but I personally see most of this as being upstream's responsibility or decision, not ours. And regarding the potential for having two commits chained—the first being upstream code, and the second any intermediary build not yet released—I think the additional complexity is justified by the deterministic builds and making it absolutely clear what is being built.

e.g. using this method, even if someone requests some earlier upstream code, for some reason—say a regression has been discovered on latest 'stable', building a fix is very easy, even though the numbering would come part-way through a current release. It also enables easy updates of the build packaging itself, even if upstream hasn't changed (such as happened for the `XL9_5_STABLE` branch).

**Comment by LamaAni** [comment]
Hi

I understand the reasoning, and it is logical. But it would make things very hard. And example can be given in airflow. When I talk about airflow 1.10.4, with image build 1.10.4 everyone know what I am talking about.

Thanks for considering, 
You can close this.

**Comment by tiredpixel** [comment]
Yes, completely understood—and that is indeed how we manage versions of pretty much everything else. :) But for pretty much everything else, the packaging is tied to the underlying code, whereas in this case, we are 'just' repackaging the upstream, without being able to affect the upstream versioning. e.g. with 10.1.2 , what would that mean for this project? That it's Postgres-XL 10.1.2 ? What if we need to update or fix an image issue? Should that be 10.1.3 ? And if Postgres-XL update some commits with some fixes on the stable branch? 10.1.4 ? And if we need to revert to a previous version of Postgres-XL code, or even just build it for something someone is analysing, but use the latest image stuff without known bugs? 10.1.5 doesn't make sense for that. Or if we want to go back to 9.4.3 , but fix with the latest image stuff? Well, the version of upstream Postgres-XL hasn't changed… Hence why, despite the long rather unwieldy version numbers, my current thinking is that this system is the best for declarative versioning, allowing us to update or build a variety of upstream Postgres-XL versions in parallel (e.g. we're currently packaging v9 and v10), without having to maintain some lookup chart of versions, or wait for a new Postgres-XL version every time we want to update the build packaging.

**Comment by tiredpixel** [comment]
p.s. If Postgres-XL tagged their commits more nicely—the ones in the source code repository are very much inconsistent, and typically updated sporadically—then the versioning of the images under this method would be far clearer anyway. e.g. if Postgres-XL chose to tag their latest commit in the v10 stable branch as 10.3.0 today, then in fact this would result in us also changing our main image releases to simply 10.3.0 . I've already relaxed the versioning here to allow non-annotated tags, since Postgres-XL annotated v9 stable branch, but not v10—but really, the tagging there is far from what I would ultimately hope for, without wanting to sound overly critical.

**Comment by LamaAni** [comment]
Hi

Thanks for the detailed response. I guess the current tagging system will have to do. The change is for the better.

**Comment by tiredpixel** [comment]
No worries. If you feel like it, and wish to request of upstream Postgres-XL project that it tag their 'stable' branch releases more sensibly and consistently, not only would I also be very pleased, but also that would trickle into this project, and make the tags here more like you describe 'automatically'—thus simplifying the Helm charts, also.

Sadly, I've pretty much given up on contacting the mailing list myself, because since their migration to a new mailing list host a year or two ago, the end-to-end encryption-through-transport guarantees have been broken, meaning I can no longer reply to people or email there. I reported it a couple of times, once at length including headers, and it apparently seemed to be a problem with the mailing list host they migrated to—but ultimately nothing got fixed, and years later, at least as of a few months ago, all my emails were still getting rejected (since I use a mailing host which enables requests of end-to-end encryption-through-transport guarantees). I confess that after the first few times, I stopped posting and all but forgot about it.
