### ISSUE TITLE
Adding contrib

### ISSUE THREAD

**Issue by stephenstubbs** [pavouk-0/postgres-xl-docker#42]
Hi,

Would it be possible to add contrib packages to this image or perhaps on another tag? 

The standard postgres image comes with most of them all compiled. I only need ltree and cube currently but it might be better to compile them all.

If not I can create a new image based off of this one but I would rather use this if possible.

Thanks

**Comment by tiredpixel** [comment]
Unsure; there are rather a lot… I don't really want to make the image bloated or take far longer to compile, unless there's enough of a reason to do so. PostgreSQL itself coming with most of these extensions enabled is a compelling reason (do you perhaps have a link?).

Another tag is perhaps tempting, otherwise—but then there'd be double the amount of things to test prior to release.

Do you know if anyone else is in favour of this proposal? :)

**Comment by stephenstubbs** [comment]
You right there quite a few and some (dblink being an example) don't seem to work with postgres xl. I don't think anyone else needs this at the moment and the helm chart does let you specify your own image so I can just use my own one for the time being. I guess if more people need this it would make sense to add some.
