### ISSUE TITLE
Where should I access postgres XL?

### ISSUE THREAD

**Issue by dan-developer** [pavouk-0/postgres-xl-docker#51]
I up the containers from the swarm example.

I exposed port 5432 from cordinator 1 to the host. Is this the port my application should connect to?

I tried to connect on port 5432 and it says that the postgres user is not in the list for the ip they are trying to access. Where do I configure so that any IP can connect to port 5432?

Where do I set up to create a user to be able to connect to, for example developer with password 123456?

Thanks.

**Comment by tiredpixel** [comment]
You should access it on 5432 from a Coordinator (it does not matter which one).

Take a look at `pg_hba.conf` in the data dir on the Coordinator; the IP range you want to allow should probably be written there, depending on how you've exposed the port. Remember to still allow the cluster to communicate freely.

If you're still having problems, it would be useful if you could paste your Coordinator's `pg_hba.conf` here.

Users should be set up by connecting to a Coordinator using `psql`. You can use standard PostgreSQL approach the first time you connect, and use the superuser as a local connection (by using `docker exec -it db_coord_1_123 psql -U postgres` or similar); then, you won't need a password, since you'll be going through the container and connecting as a local connection.

Remember to never modify anything manually on the Datanodes; everything should go through Coordinator nodes (standard Postgres-XL).

**Comment by tiredpixel** [comment]
One more thing worth mentioning: it's worth checking which Docker network ranges have been assigned to the 2 networks (cluster comms, and external access through Coordinators). The cluster comms one *must* have a lower-value subnet than the other. Normally, this happens, but I have sometimes seen weird things happen.

**Comment by tiredpixel** [comment]
Remember you don't need to build the images in order to use this project; it's only necessary if you want to, or to contribute to the project. All images are built and published to Docker Hub by us at Pavouk:
https://www.pavouk.tech/2019/10/25/postgres-xl-docker-releases-2/
You could look at these for an example setup which should work out-the-box:
https://github.com/pavouk-0/postgres-xl-docker/blob/master/docker-compose.image.yml
https://github.com/pavouk-0/postgres-xl-docker/blob/master/bin/init-eg

**Comment by dan-developer** [comment]
Thanks for the answer.
My intention is to contribute strongly to the project, but first I want to make it work for an existing project I developed in python / django.
After that I intend to make pull requests with improvements that can be made from my point of view.

**Comment by dan-developer** [comment]
Another question:

Se eu utilizar em produção. Como faço para subir no swarm mais um data node?

**Comment by tiredpixel** [comment]
Excellent. Sounds like this setup is indeed what you want, then. If running on Docker (non-Swarm) locally, I recommend you use `bin/init-eg` to auto-install a development environment for you.

**Comment by tiredpixel** [comment]
For that, you can look at
https://github.com/pavouk-0/postgres-xl-docker/blob/master/docker-compose.swarm.yml
https://github.com/pavouk-0/postgres-xl-docker/blob/master/bin/init-eg-swarm
It's fine if you prefer to create and run the init statements manually, even pasting into each db if you prefer (including the datanodes, in this case), if you don't want to use `init-eg-swarm`.
I recommend that you copy the example `docker-compose.swarm.yml`, and adapt it to your own use (e.g. do you want just 2 datanodes, or perhaps more? or just 1 coordinator? or 3? all of that is supported in this project), and then you should be able to use `docker stack deploy` or similar.

**Comment by tiredpixel** [comment]
Remember that if you have more than one node in your Swarm cluster, and don't have network or somehow-shared data storage cross-node, you *must* constrain the datanodes to be bound to the host. Otherwise, they'll lose their volumes and attempt to init another, and the cluster will likely break horribly. :)

**Comment by dan-developer** [comment]
Thanks for the answers. I will use it in a system in production. I will go adapting, and where I see that can be improved, I will send pull requests.

**Comment by tiredpixel** [comment]
This appears to be sorted.
