### ISSUE TITLE
Deploy to Kubernetes cluster by docker stack 

### ISSUE THREAD

**Issue by urpylka** [pavouk-0/postgres-xl-docker#55]
Hi! **I want to use Postgres-XL on Kubernetes cluster**. I am interesting to do it through `docker stack`, because it works with `docker-compose.yml` and can be running at `docker-compose` or `Kubernetes`.

I am interesting to know what do you think about that?

PS yesterday I'd already tried to run that, but I don't know how to make automatic initialization of the cluster. Or how to dynamic reconfigure cluster with ReplicaSet or another methods? Is it needed to change `NODE` records in each node after every change of the structure?

**Comment by tiredpixel** [comment]
Hi! Yes, it should work on a Kubernetes cluster. You might like to take a look at `docker-compose.image.yml` and `docker-compose.swarm.yml` to get started; `docker stack deploy` should work for that on Docker Swarm, so I suppose something similar should work for Kubernetes, too, if there is support for that there.

I'm not actively working with Kubernetes, at present, but from memory something like a ReplicaSet would be the way to go. That is, you'll want automatic respawning of crashed containers, but with persistent volumes through some storage driver. Mm, depends abut the node records; in general, you'd define a certain structure, and have those automatically respawning. But if you're planning to add and remove nodes, you'll have more considerations anyway, since you'll have to deal with rebalancing nodes and ensuring slots are covered, etc. I personally haven't tried changing the topology of a Postgres-XL cluster once it's defined.

**Comment by urpylka** [comment]
Hi! I've made the PR with configurations to deploy Kubernetes cluster by docker-stack.
Also it consists pgpool & wait-for-it service.
Please check my PR https://github.com/tiredpixel/postgres-xl-docker/pull/56.

Thanks!

**Comment by tiredpixel** [comment]
Many thanks for your contribution! I see there's a lot to cover, so it'll likely take more than one round. However, I'll add my initial thoughts at first glance now (I haven't tried to run anything, so I'll assume it works ;) ).

**Comment by urpylka** [comment]
Ok, I am ready to support by continue contributions and keep contact. Ask me whenever you need

**Comment by tiredpixel** [comment]
Since #56 is merged, I think this is resolved.
